Bstructure/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('master.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

master/urls.py
from django.urls import path, include
from django.views import View
from .import views

urlpatterns = [
    path("", views.index, name="index"),
    path("tree",views.display_employee_hierarchy, name="employee"),
    path('employeet/', views.employee_list, name='employee_list'),
    path('edit-employee/<int:employee_id>/', views.edit_employee, name='edit_employee'),

    path('login/', views.login, name='login'),
    path('userpro/', views.userpro, name='userpro'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.custom_register, name='register'),

    path('api/change-password/', views.ChangePasswordView.as_view(), name='change-password'),


]

master/models.py
from django.db import models
from django.contrib.auth.models import User

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    report_to = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    position_name = models.CharField(max_length=100) 

    def __str__(self):
        return self.user.username

master/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from master.fomrs import EmployeeForm
from django.contrib.auth import authenticate, login

from master.models import Employee

from django.contrib import messages
from django.contrib.auth.models import User,auth

# Create your views here.



def index(request):
    return HttpResponse("The Server is up!!")




def display_employee_hierarchy(request):
    # Assuming have a CEO instance as the root of the hierarchy
    ceo = Employee.objects.get(position_name='ceo')

    return render(request, 'employee_tree.html', {'employee': ceo})



def employee_list(request):
    employees = Employee.objects.all()
    return render(request, 'employee_list.html', {'employees': employees})



def edit_employee(request, employee_id):
    employee = get_object_or_404(Employee, id=employee_id)
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('employee_list')  
    else:
        form = EmployeeForm(instance=employee)
    return render(request, 'edit_employee.html', {'form': form})



def custom_register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if password1 != password2:
            messages.error(request, 'Passwords do not match.')
        else:
            # Check if the username is unique
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username is already taken.')
            else:
                # Create the user
                user = User.objects.create_user(username=username, password=password1)
             
                user.save()
                messages.success(request, 'Registration successful.')
                return redirect('employee_list') 

    return render(request, 'register.html')

   
def userpro(request):
    if request.user.is_authenticated:
        data=User.objects.all()
       
        context={'data':data}
        return render(request, 'userpro.html',context)
    auth.logout(request)     
    return render(request, 'login.html')

def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
        #request.session.flush()
        return redirect(login)
    
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:           
            auth.login(request,user)
            return redirect('userpro')
        else:
            messages.error(request, 'Invalid username or password. Please try again.')

    return render(request, 'login.html') 

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib.auth.models import User
from rest_framework.permissions import IsAuthenticated
 
from .serializers import ChangePasswordSerializer


class ChangePasswordView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, format=None):
        serializer = ChangePasswordSerializer(data=request.data, context={'request': request})

        if serializer.is_valid():
            user = request.user

            old_password = serializer.validated_data['old_password']
            new_password = serializer.validated_data['new_password']

            if user.check_password(old_password):
                user.set_password(new_password)
                user.save()
                return Response({'message': 'Password updated successfully'}, status=status.HTTP_200_OK)
            else:
                return Response({'error': 'Invalid old password'}, status=status.HTTP_400_BAD_REQUEST)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

templates/change_form.html
change_form 

templates/edit_employee.html
<!-- edit_employee.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Employee</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1>Edit Employee</h1>
        <form method="post" class="mt-3">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="{{ form.user.id_for_label }}">Username</label>
                {{ form.user }}
            </div>
            <div class="form-group">
                <label for="{{ form.user.id_for_label }}">report_to</label>
                {{ form.report_to }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.position_name.id_for_label }}">Position</label>
                {{ form.position_name }}
            </div>
          

            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
    </div>
</body>
</html>

templates/employee_list.html
<!-- employee_list.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Employee List</title>
</head>
<body>
    <h1>Employee List</h1>
    <table>
        <thead>
            <tr>
                <th>Username</th>
                <th>Position</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>
                <td>{{ employee.user.username }}</td>
                <td>{{ employee.position_name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/employee_tree.html
<!DOCTYPE html>
<html>
<head>
    <title>Employee Hierarchy</title>
    <style>
        .employee-container {
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            padding: 10px;
        }

        .ceo {
            background-color: #ff5733;
            border-radius: 50%;
            width: 80px;
            height: 80px;
            line-height: 80px;
            color: white;
            font-weight: bold;
        }

        .manager {
            background-color: #3498db;
            color: white;
            padding: 10px;
            border-radius: 10px;
            cursor: pointer;
        }

        .employee {
            background-color: #e5e5e5;
            padding: 5px;
            border-radius: 5px;
        }
        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0,0,0,0.7);
        }

        .modal-content {
            background-color: #fff;
            margin: 15% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 50%;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }

        /* Style for the close button */
        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
    </style>
</head>
{% block content %}

<body> 
   
    <ul>
        <li class="employee-container">
           
            <div class="{{ employee.position_name|lower }}">
                {{ employee.user.username }} -  {{ employee.position_name }}
            </div>
        </li>
        {% for subordinate in employee.employee_set.all %}
            <li class="employee-container">
                <button id="addEmployeeButton" onclick="editEmployee({{ subordinate.id }})">+</button>
                <div class="{{ subordinate.position_name|lower }}" onclick="toggleEmployees(this)">
                    {{ subordinate.user.username }} -  {{ subordinate.position_name }}
                </div>
                <ul style="display: none;"> 
                    {% for sub_subordinate in subordinate.employee_set.all %}
                        <li class="employee-container">
                            <button id="addEmployeeButton" onclick="editEmployee({{ sub_subordinate.id }})">+</button>
                            <div class="{{ sub_subordinate.position_name|lower }}" onclick="toggleEmployees(this)">
                                {{ sub_subordinate.user.username }} - {{ sub_subordinate.position_name }}
                            </div>
                            <ul style="display: none;"> 
                                {% for sub__subordinate in sub_subordinate.employee_set.all %}
                                    <li class="employee-container">
                                        <button id="addEmployeeButton" onclick="editEmployee({{ sub__subordinate.id }})">+</button>
                                        <div class="{{ sub__subordinate.position_name|lower }}">
                                            {{ sub__subordinate.user.username }} - {{ sub__subordinate.position_name }}
                                        </div>
                                    </li>
                                {% empty %}
                                    <li>No subordinate</li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% empty %}
                       <li>No subordinate</li>
                    {% endfor %}
                </ul>
            </li>
        {% empty %}
           <li>No subordinate</li>
        {% endfor %}
    </ul>
    

    <script>
        function toggleEmployees(managerElement) {
            const employeesList = managerElement.nextElementSibling;
            if (employeesList.style.display === 'none') {
                employeesList.style.display = 'block';
            } else {
                employeesList.style.display = 'none';
            }
        }

        function editEmployee(employeeId) {
            window.location.href = `/edit-employee/${employeeId}/`;
        }
    
 
        const addButton = document.getElementById('addEmployeeButton');
        const modal = document.getElementById('myModal');
        const closeModal = document.getElementById('closeModal');

        addButton.addEventListener('click', function() {
            modal.style.display = 'block';
        });

        closeModal.addEventListener('click', function() {
            modal.style.display = 'none';
        });

        // Close the modal if the user clicks anywhere outside of it
        window.addEventListener('click', function(event) {
            if (event.target == modal) {
                modal.style.display = 'none';
            }
        });
    </script>
</body>
</html>
{% endblock %}

templates/login.html
{% block content %}
<!-- Add Bootstrap CSS and JavaScript -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<section class="container-fluid py-5">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-4">
            <div class="container h-100">
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-5">
                        <form class="form-container" action="{% url 'login' %}" method="post">
                            {% csrf_token %}
                            {% for message in messages %}
                                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                            <h4 class="text-center font-weight-bold">LOGIN</h4>
                            <div class="form-group">
                                <label for="InputEmail1">User name</label>
                                <input type="text" class="form-control" id="InputEmail1" placeholder="Enter username" name="username">
                            </div>
                            <div class="form-group">
                                <label for="InputPassword1">Password</label>
                                <input type="password" class="form-control" id="InputPassword1" placeholder="Password" name="password">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </section>
</section>
{% endblock %}

templates/register.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% block content %}
<section class="container-fluid py-5">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-4">
            <div class="container h-100">
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-5">
                        <form class="form-container" method="post">
                            {% csrf_token %}
                            {% for message in messages %}
                                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                            <h4 class="text-center font-weight-bold">REGISTER</h4>
                            <div class="form-group">
                                <label for="id_username">Username</label>
                                <input type="text" class="form-control" id="id_username" name="username" required>
                            </div>
                            <div class="form-group">
                                <label for="id_password1">Password</label>
                                <input type="password" class="form-control" id="id_password1" name="password1" required>
                            </div>
                            <div class="form-group">
                                <label for="id_password2">Confirm Password</label>
                                <input type="password" class="form-control" id="id_password2" name="password2" required>
                            </div>
                           
                            <button type="submit" class="btn btn-primary btn-block">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </section>
</section>
{% endblock %}

templates/userpro.html
<table class="table table-bordered">
    <tbody>
        <tr>
            <th>User ID</th>
            <td>{{user.id}}</td>
        </tr>
        <tr>
            <th>Username</th>
            <td>{{user.username}}</td>
        </tr>
        
        <tr>
            <th>join Date</th>
            <td>{{ user.date_joined }}</td>
        </tr>
    </tbody>
</table>
<a href="{% url 'logout' %}"> <button class="btn btn-primary">LOGOUT</button>
</div>